spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 690288168069-hhk5nu5ftkvaoqblmutpet7h6sgod7k2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: Ov23lirkVjoBmtm2ZSrJ
            client-secret: bad1d624c802d0e4a472e0024753154c4328031e

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8
jwt:
  issuer: tnghks023@naver.com
  secret_key: test_key