spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-id}
            client-secret: ${google-secret}
            scope:
              - email
              - profile
          github:
            client-id: ${github-id}
            client-secret: ${github-secret}

#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      encoding: UTF-8
jwt:
  issuer: tnghks023@naver.com
  secret_key: test_key